export interface CategoryQuestion {
  question_order: number;
  question_text: string;
  question_type: 'multiple_choice' | 'text' | 'number';
  options?: string[];
  required: boolean;
  output_key: string;
}

export interface CategoryConfig {
  category: string;
  category_description: string;
  trade?: string;
  questions: CategoryQuestion[];
}

export const categoryConfig: CategoryConfig[] = [
  {
    category: 'Boilers',
    category_description: 'Central heating systems, boiler installation, etc.',
    trade: 'Plumbing',
    questions: [
      {
        question_order: 1,
        question_text: 'What type of boiler do you have?',
        question_type: 'multiple_choice',
        options: ['Gas', 'Oil', 'Electric', 'Other/Not sure'],
        required: true,
        output_key: 'boilers_q1',
      },
      {
        question_order: 2,
        question_text: 'What needs doing to the boiler?',
        question_type: 'multiple_choice',
        options: ['Repair', 'Service', 'Installation', 'Removal', 'Gas safety certificate'],
        required: true,
        output_key: 'boilers_q2',
      },
      {
        question_order: 3,
        question_text: 'Is the property domestic or commercial?',
        question_type: 'multiple_choice',
        options: ['Domestic', 'Commercial'],
        required: true,
        output_key: 'boilers_q3',
      },
      {
        question_order: 4,
        question_text: 'Add a short description of the job (include any useful details).',
        question_type: 'text',
        required: false,
        output_key: 'description',
      },
    ],
  },
  {
    category: 'Radiators',
    category_description: 'Radiators installation, repairs, etc.',
    trade: 'Plumbing',
    questions: [
      {
        question_order: 1,
        question_text: 'What do you need help with?',
        question_type: 'multiple_choice',
        options: ['Install new radiator', 'Move existing radiator', 'Repair leak', 'Cold radiator issue'],
        required: true,
        output_key: 'radiators_q1',
      },
      {
        question_order: 2,
        question_text: 'How many radiators are involved (approx)?',
        question_type: 'multiple_choice',
        options: ['1-2', '3-5', '6+'],
        required: true,
        output_key: 'radiators_q2',
      },
      {
        question_order: 3,
        question_text: 'Is this for a domestic or commercial property?',
        question_type: 'multiple_choice',
        options: ['Domestic', 'Commercial'],
        required: true,
        output_key: 'radiators_q3',
      },
      {
        question_order: 4,
        question_text: 'Add a short description of the job (include any useful details).',
        question_type: 'text',
        required: false,
        output_key: 'description',
      },
    ],
  },
  {
    category: 'Appliances',
    category_description: 'Dishwasher, washing machine, etc.',
    trade: 'Plumbing',
    questions: [
      {
        question_order: 1,
        question_text: 'Which appliance do you need help with?',
        question_type: 'multiple_choice',
        options: ['Dishwasher', 'Washing machine', 'Fridge/Freezer', 'Other'],
        required: true,
        output_key: 'appliances_q1',
      },
      {
        question_order: 2,
        question_text: 'What needs doing?',
        question_type: 'multiple_choice',
        options: ['Installation', 'Replacement', 'Repair', 'Removal'],
        required: true,
        output_key: 'appliances_q2',
      },
      {
        question_order: 3,
        question_text: 'Is the property domestic or commercial?',
        question_type: 'multiple_choice',
        options: ['Domestic', 'Commercial'],
        required: true,
        output_key: 'appliances_q3',
      },
      {
        question_order: 4,
        question_text: 'Add a short description of the job (include any useful details).',
        question_type: 'text',
        required: false,
        output_key: 'description',
      },
    ],
  },
  {
    category: 'Fixtures',
    category_description: 'Shower, toilet, sink, etc.',
    trade: 'Plumbing',
    questions: [
      {
        question_order: 1,
        question_text: 'Which fixture needs attention?',
        question_type: 'multiple_choice',
        options: ['Shower', 'Toilet', 'Sink', 'Bath', 'Other'],
        required: true,
        output_key: 'fixtures_q1',
      },
      {
        question_order: 2,
        question_text: 'What is the issue?',
        question_type: 'multiple_choice',
        options: ['Install new', 'Repair', 'Blocked', 'Leaking'],
        required: true,
        output_key: 'fixtures_q2',
      },
      {
        question_order: 3,
        question_text: 'Is the property domestic or commercial?',
        question_type: 'multiple_choice',
        options: ['Domestic', 'Commercial'],
        required: true,
        output_key: 'fixtures_q3',
      },
      {
        question_order: 4,
        question_text: 'Add a short description of the job (include any useful details).',
        question_type: 'text',
        required: false,
        output_key: 'description',
      },
    ],
  },
  {
    category: 'Pipework, taps & drainage',
    category_description: 'Pipe alterations, blockages, leaks, macerator, etc.',
    trade: 'Plumbing',
    questions: [
      {
        question_order: 1,
        question_text: 'What best describes the job?',
        question_type: 'multiple_choice',
        options: ['Leak repair', 'Pipe alteration', 'Blocked pipe', 'Replace tap', 'Install new tap'],
        required: true,
        output_key: 'pipework,_taps_and_drainage_q1',
      },
      {
        question_order: 2,
        question_text: 'Is this an urgent issue?',
        question_type: 'multiple_choice',
        options: ['Yes', 'No', 'Unsure'],
        required: true,
        output_key: 'pipework,_taps_and_drainage_q2',
      },
      {
        question_order: 3,
        question_text: 'Is the property domestic or commercial?',
        question_type: 'multiple_choice',
        options: ['Domestic', 'Commercial'],
        required: true,
        output_key: 'pipework,_taps_and_drainage_q3',
      },
      {
        question_order: 4,
        question_text: 'Add a short description of the job (include any useful details).',
        question_type: 'text',
        required: false,
        output_key: 'description',
      },
    ],
  },
  {
    category: 'Boilers (gas)',
    category_description: 'Gas boiler installation, repair, service, etc.',
    trade: 'Gas Engineer',
    questions: [
      {
        question_order: 1,
        question_text: 'What fuel does your boiler use?',
        question_type: 'multiple_choice',
        options: ['Natural gas', 'LPG', 'Not sure'],
        required: true,
        output_key: 'boilers_gas_q1',
      },
      {
        question_order: 2,
        question_text: 'What needs doing?',
        question_type: 'multiple_choice',
        options: ['Installation / Replacement', 'Repair', 'Service', 'Removal / Relocation', 'Gas safety check'],
        required: true,
        output_key: 'boilers_gas_q2',
      },
      {
        question_order: 3,
        question_text: 'Property type',
        question_type: 'multiple_choice',
        options: ['House', 'Flat', 'Bungalow', 'Other'],
        required: true,
        output_key: 'boilers_gas_q3',
      },
      {
        question_order: 4,
        question_text: 'Add a short description of the job (include any useful details).',
        question_type: 'text',
        required: false,
        output_key: 'description',
      },
    ],
  },
  {
    category: 'Gas hobs, cookers & ovens',
    category_description: 'Gas hob, cooker, oven installation, repair, etc.',
    trade: 'Gas Engineer',
    questions: [
      {
        question_order: 1,
        question_text: 'Which appliance?',
        question_type: 'multiple_choice',
        options: ['Gas hob', 'Gas cooker (freestanding)', 'Gas oven', 'Gas range cooker'],
        required: true,
        output_key: 'gas_hobs_cookers_and_ovens_q1',
      },
      {
        question_order: 2,
        question_text: 'What needs doing?',
        question_type: 'multiple_choice',
        options: ['Install new', 'Replace existing', 'Repair', 'Disconnect / remove'],
        required: true,
        output_key: 'gas_hobs_cookers_and_ovens_q2',
      },
      {
        question_order: 3,
        question_text: 'Property type',
        question_type: 'multiple_choice',
        options: ['House', 'Flat', 'Bungalow', 'Other'],
        required: true,
        output_key: 'gas_hobs_cookers_and_ovens_q3',
      },
      {
        question_order: 4,
        question_text: 'Add a short description of the job (include any useful details).',
        question_type: 'text',
        required: false,
        output_key: 'description',
      },
    ],
  },
  {
    category: 'Gas fires & flues',
    category_description: 'Gas fire, stove, flue lining, back boiler, etc.',
    trade: 'Gas Engineer',
    questions: [
      {
        question_order: 1,
        question_text: 'What type of unit?',
        question_type: 'multiple_choice',
        options: ['Gas fire (decorative)', 'Gas stove', 'Flue / chimney lining', 'Back boiler'],
        required: true,
        output_key: 'gas_fires_and_flues_q1',
      },
      {
        question_order: 2,
        question_text: 'What needs doing?',
        question_type: 'multiple_choice',
        options: ['Install new', 'Service', 'Repair', 'Removal'],
        required: true,
        output_key: 'gas_fires_and_flues_q2',
      },
      {
        question_order: 3,
        question_text: 'Property type',
        question_type: 'multiple_choice',
        options: ['House', 'Flat', 'Bungalow', 'Other'],
        required: true,
        output_key: 'gas_fires_and_flues_q3',
      },
      {
        question_order: 4,
        question_text: 'Add a short description of the job (include any useful details).',
        question_type: 'text',
        required: false,
        output_key: 'description',
      },
    ],
  },
  {
    category: 'Gas safety certificates (CP12)',
    category_description: 'Landlord / homeowner gas safety certificates.',
    trade: 'Gas Engineer',
    questions: [
      {
        question_order: 1,
        question_text: 'Which certificate?',
        question_type: 'multiple_choice',
        options: ['Landlord gas safety (CP12)', 'Homeowner gas safety check', 'New tenancy certificate', 'Sale of property certificate'],
        required: true,
        output_key: 'gas_safety_certificates_cp12_q1',
      },
      {
        question_order: 2,
        question_text: 'How many gas appliances to test?',
        question_type: 'multiple_choice',
        options: ['1', '2–3', '4+'],
        required: true,
        output_key: 'gas_safety_certificates_cp12_q2',
      },
      {
        question_order: 3,
        question_text: 'Property type',
        question_type: 'multiple_choice',
        options: ['House', 'Flat', 'Bungalow', 'Other'],
        required: true,
        output_key: 'gas_safety_certificates_cp12_q3',
      },
      {
        question_order: 4,
        question_text: 'Add a short description of the job (include any useful details).',
        question_type: 'text',
        required: false,
        output_key: 'description',
      },
    ],
  },
  {
    category: 'Gas leaks & emergency',
    category_description: 'Smell of gas, suspected leak, CO alarm, emergency call-out.',
    trade: 'Gas Engineer',
    questions: [
      {
        question_order: 1,
        question_text: 'What is the issue?',
        question_type: 'multiple_choice',
        options: ['Smell of gas', 'Suspected leak', 'Carbon monoxide alarm triggered', 'Boiler has shut down'],
        required: true,
        output_key: 'gas_leaks_and_emergency_q1',
      },
      {
        question_order: 2,
        question_text: 'How urgent?',
        question_type: 'multiple_choice',
        options: ['Now (emergency)', 'Within 24 hours', 'Within a few days'],
        required: true,
        output_key: 'gas_leaks_and_emergency_q2',
      },
      {
        question_order: 3,
        question_text: 'Property type',
        question_type: 'multiple_choice',
        options: ['House', 'Flat', 'Bungalow', 'Other'],
        required: true,
        output_key: 'gas_leaks_and_emergency_q3',
      },
      {
        question_order: 4,
        question_text: 'Add a short description of the job (include any useful details).',
        question_type: 'text',
        required: false,
        output_key: 'description',
      },
    ],
  },
  {
    category: 'Gas pipework',
    category_description: 'New pipe runs, alterations, capping, meter relocation.',
    trade: 'Gas Engineer',
    questions: [
      {
        question_order: 1,
        question_text: 'What best describes the job?',
        question_type: 'multiple_choice',
        options: ['New gas pipe run', 'Pipe alteration / extension', 'Pipe capping', 'Meter relocation'],
        required: true,
        output_key: 'gas_pipework_q1',
      },
      {
        question_order: 2,
        question_text: 'Approximate length / scale?',
        question_type: 'multiple_choice',
        options: ['Short (under 2m)', 'Medium (2–5m)', 'Long (5m+) / Major'],
        required: true,
        output_key: 'gas_pipework_q2',
      },
      {
        question_order: 3,
        question_text: 'Property type',
        question_type: 'multiple_choice',
        options: ['House', 'Flat', 'Bungalow', 'Other'],
        required: true,
        output_key: 'gas_pipework_q3',
      },
      {
        question_order: 4,
        question_text: 'Add a short description of the job (include any useful details).',
        question_type: 'text',
        required: false,
        output_key: 'description',
      },
    ],
  },
];
