// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtchveaqdxigczojawcv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0Y2h2ZWFxZHhpZ2N6b2phd2N2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2ODQ5MDUsImV4cCI6MjA3MzI2MDkwNX0.HRuHUarx5mHwFr2d_cw1wrYZ3t_9QPPn_Kwk8xnZxdw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});